# Generated by Django 5.0.4 on 2024-04-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='children',
            old_name='date_of_admission',
            new_name='dateOfAdmission',
        ),
        migrations.RenameField(
            model_name='children',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='children',
            old_name='legal_guardian',
            new_name='legalGuardian',
        ),
        migrations.RenameField(
            model_name='children',
            old_name='place_of_bitrh',
            new_name='placeOfBirth',
        ),
        migrations.RenameField(
            model_name='children',
            old_name='referral_number',
            new_name='referralNumber',
        ),
        migrations.RemoveField(
            model_name='children',
            name='notes',
        ),
        migrations.AddField(
            model_name='children',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='children',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
