# Generated by Django 5.0.4 on 2024-04-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_date_of_admission_children_dateofadmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='image',
        ),
    ]
