# Generated by Django 5.0.4 on 2024-05-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_children_dateofadmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='children_images/'),
        ),
    ]
